[package]
name = "rust-bus"
version = "0.12.0"
authors = ["Ben Boeckel <mathstuf@gmail.com>"]
license = "BSD-3-Clause"
description = """
Library for exposing a D-Bus interface.
"""

[dependencies]
bitflags = "~0.6"
dbus-serialize = "~0.1.1"

[dependencies.dbus-bytestream]
git = "https://github.com/srwalter/dbus-bytestream.git"

[dependencies.machine-id]
git = "https://github.com/mathstuf/rust-machine-id"

[lib]
name = "bus"
path = "src/lib.rs"
