[package]
name = "rust-ez-dbus"
version = "0.12.0"
authors = ["Ben Boeckel <mathstuf@gmail.com>"]
license = "BSD"
description = """
Convenience wrappers for exposing a D-Bus interface.
"""

[dependencies]
dbus-serialize = "~0.1.1"

[dependencies.dbus-bytestream]
git = "https://github.com/mathstuf/dbus-bytestream.git"
branch = "impl-error-trait"

[lib]
name = "ez_dbus"
path = "src/lib.rs"
