[package]
name = "rust-ez-dbus"
version = "0.12.0"
authors = ["Ben Boeckel <mathstuf@gmail.com>"]
license = "BSD"
description = """
Convenience wrappers for exposing a D-Bus interface.
"""

[dependencies]
dbus = "0.1.1"

[lib]
name = "ez_dbus"
path = "src/lib.rs"
