[package]
name = "rust-ez-dbus"
version = "0.12.0"
authors = ["Ben Boeckel <mathstuf@gmail.com>"]
license = "BSD-3-Clause"
description = """
Convenience wrappers for exposing a D-Bus interface.
"""

[dependencies]
dbus-bytestream = "~0.1.3"
dbus-serialize = "~0.1.1"
log = "~0.3.2"
machine-id = "~0.2.1"

[lib]
name = "ez_dbus"
path = "src/lib.rs"
